### ISSUE TITLE
Can't build from source!

### ISSUE THREAD

**Issue by hamad12a** [wong2/chatgpt-google-extension#225]
Under Linux environment specifically pop!_os ubuntu flavor
I execute `npm install` to install the dependencies
then `npm run build` it throws
```
(node:221624) UnhandledPromiseRejectionWarning: TypeError: fs.rm is not a function
    at Object.remove (/home/mypop/Downloads/Firefox_Addons/chatgpt-google-extension/node_modules/fs-extra/lib/remove/index.js:7:6)
    at /home/mypop/Downloads/Firefox_Addons/chatgpt-google-extension/node_modules/universalify/index.js:10:14
    at new Promise (<anonymous>)
    at Object.remove (/home/mypop/Downloads/Firefox_Addons/chatgpt-google-extension/node_modules/universalify/index.js:7:14)
    at deleteOldDir (file:///home/mypop/Downloads/Firefox_Addons/chatgpt-google-extension/build.mjs:15:12)
    at build (file:///home/mypop/Downloads/Firefox_Addons/chatgpt-google-extension/build.mjs:71:9)
    at file:///home/mypop/Downloads/Firefox_Addons/chatgpt-google-extension/build.mjs:107:1
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(node:221624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:221624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

**Comment by hamad12a** [comment]
Before above description encountered I noticed an incompatibility between the dependencies and the version of nodejs I am using which is actually v12.22.9.

**Comment by ioneliabuzatu** [comment]
it needs nodejs>=18.0.0 i had to install it to v18 to make it work
